# welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
print("Hello world")

Hello world


In [3]:
myarr=np.array([[2,34,5,432,22]], np.int8)

In [4]:
myarr

array([[  2,  34,   5, -80,  22]], dtype=int8)

In [5]:
myarr[0]

array([  2,  34,   5, -80,  22], dtype=int8)

In [6]:
myarr.shape

(1, 5)

In [7]:
myarr.dtype

dtype('int8')

In [8]:
myarr[0,1]=45

In [9]:
myarr

array([[  2,  45,   5, -80,  22]], dtype=int8)

In [10]:
listarray=np.array([[2,3,4],[23,21,45],[45,12,34]])

In [11]:
listarray

array([[ 2,  3,  4],
       [23, 21, 45],
       [45, 12, 34]])

In [12]:
listarray.shape


(3, 3)

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.size

9

In [15]:
np.array({2,45})

array({2, 45}, dtype=object)

In [16]:
zeros=np.zeros((2,5))

In [17]:
zeros.shape

(2, 5)

In [18]:
rng=np.arange(14)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [20]:
lspace=np.linspace(1,4,4)

In [21]:
lspace

array([1., 2., 3., 4.])

In [22]:
emp=np.empty((4,6))

In [23]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.95819673e-306,
        7.56587585e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 1.33511290e-306,
        1.78019082e-306, 8.45559303e-307, 8.06613465e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 9.79107193e-307, 3.33509775e-317]])

In [24]:
ide=np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.shape

(45, 45)

In [27]:
arr=np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr=arr.reshape(3,33)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr=arr.ravel()

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
x=[[1,2,3], [4,5,6],[7,8,9]]

In [34]:
ar=np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [37]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
ar.flat

In [39]:
for item in ar.flat:
 print(item)

1
2
3
4
5
6
7
8
9


In [40]:
ar.size

9

In [41]:
one=np.array([1,2,4,5,6])

In [42]:
one.argmax()

4

In [43]:
one.argmin()

0

In [44]:
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
ar.argmax()

8

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
ar2=np.array([[1, 5, 3],
       [4, 15, 6],
       [7, 8, 5]])

In [49]:
ar+ar2

array([[ 2,  7,  6],
       [ 8, 20, 12],
       [14, 16, 14]])

In [50]:
ar*ar2

array([[ 1, 10,  9],
       [16, 75, 36],
       [49, 64, 45]])

In [51]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [52]:
ar.sum()

45

In [53]:
ar.min()

1

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
import sys

In [56]:
py_ar=[0,4,55,2]